config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get 'welcome/index'
  root to: 'welcome#index'
  resources :users do
    member do
      get :following, :followers, :received_comments
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :posts, only: %i[create destroy update edit show]
  resources :relationships, only: %i[create destroy]
  resources :reviews
  resources :conversations, only: %i[create destroy edit]
  resources :observerships, only: %i[create destroy]
  get '/display', to: 'noticeboards#show'
  get '/noticeboards/refresh_part'

  mount Resque::Server.new, at: '/jobs'
end

app/views/shared/_comment_form.html.erb
<%= form_with(model: @conversation, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_area :comment, placeholder: 'Leave a comment' %>
    </div>
    <%= hidden_field_tag :recipient_id, params[:id] %>
    <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error-explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items,
                    params: { controller: :welcome, action: :index } %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, placeholder: 'Compose new post...' %>
  </div>
  <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
  <span class="image">
    <%= f.label :image %>
    <%= f.file_field :image, onchange: 'check_size()', id: 'file', accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>
<%# Script below adapted from https://www.geeksforgeeks.org/validation-of-file-size-while-uploading-using-javascript-jquery/ %>
<script type="text/javascript">
  check_size = () => {
    const fi = document.getElementById('file');
    if (fi.files.length > 0) {
      for (const i = 0; i <= fi.files.length - 1; i++) {
        const fsize = fi.files.item(i).size;
        const file = Math.round((fsize/(1024*1024)));
  
        if (file >= 5) {
          alert("Maximum file size is 5MB. Please choose a smaller file.");
          document.getElementById('post_image').value = '';
        }
      }
    }
  }
</script>

app/views/shared/_review_list.html.erb
<div class="col-md-6">
  <h3>Reviews</h3>
  <div class="btn-group container">
    <% if @post.user != current_user %>
      <%= link_to 'Create review', new_review_path(id: @post.id), class: "btn btn-primary btn-block" %>
    <% end %>
  </div>
  <% if @reviews.any? %>
    <ol class="posts">
      <%= render @reviews %>
    </ol>
  <% else %>
    <div class="container">
      <div class="alert alert-info">
        There are no reviews for this post yet
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to 'Go to my profile', current_user %></span>
<span><%= pluralize(current_user.posts.count, 'post') %></span>