config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get 'welcome/index'
  root to: 'welcome#index'
  resources :users do
    member do
      get :following, :followers, :received_comments
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :posts, only: %i[create destroy update edit show]
  resources :relationships, only: %i[create destroy]
  resources :reviews
  resources :conversations, only: %i[create destroy edit]
  resources :observerships, only: %i[create destroy]
  get '/display', to: 'noticeboards#show'
  get '/noticeboards/refresh_part'

  mount Resque::Server.new, at: '/jobs'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    if logged_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/welcome/_not_logged_in.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Welcome to cyhoeddwn!</h1>
      <p class="lead text-muted">cyhoeddwn lets you display user created content on connected displays located in your community</p>
      <p>
        <%= link_to "Create an account", signup_path, class: "btn btn-primary my-2" %>
        <%= link_to "Log in", login_path, class: "btn btn-secondary my-2" %>
      </p>
    </div>
  </div>
</div>
</section>

app/views/welcome/index.html.erb
<%= provide(:title, 'Home')%>
<%= provide(:button_text, 'Post')%>
<main>
  <% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
        <section class="post_form">
          <%= render 'shared/post_form' %>
        </section>
      </aside>
      <div class="col-md-8">
        <h3>Post feed</h3>
        <%= render 'shared/feed' %>
        <% if current_user.following.count == 0 %>
          <p>Hey <%= current_user.name %>, it looks like you're not following anyone. Get started by looking at <%= link_to 'other users', users_url %> on cyhoeddwn, you can follow them by visiting their profiles!</p>
          <p>Wondering what to do first? Why not visit the <%= link_to 'user guide', 'https://help.cyhoeddwn.wales/docs/getting_started/index/' %> section of the guide?</p>
        <% end %>
      </div>
    </div>
  <% else %>
    <%= render 'not_logged_in' %>
  <% end %>
</main>