config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  get 'welcome/index'
  root to: 'welcome#index'
  resources :users do
    member do
      get :following, :followers, :received_comments
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :posts, only: %i[create destroy update edit show]
  resources :relationships, only: %i[create destroy]
  resources :reviews
  resources :conversations, only: %i[create destroy edit]
  resources :observerships, only: %i[create destroy]
  get '/display', to: 'noticeboards#show'
  get '/noticeboards/refresh_part'

  mount Resque::Server.new, at: '/jobs'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Need some more information? Visit <%= link_to "the Yggdrasil", 'https://help.cyhoeddwn.wales' %> to help you find your way.<br>
    cyhoeddwn, made with ❤️ by <a href="https://dev.becquerel.me">Genevieve Clifford</a>.
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="collapse" id="navbarToggleExternalContent">
  <div class="bg-dark p-4">
    <% if logged_in? %>
      <h5 class="text-white h4">Hi <%= current_user.name %>!</h5>
      <span class="text-muted">Links to pages that you may find useful</span>
      <li class="white-link"><%= link_to 'Home', root_path %></li>
      <li class="white-link"><%= link_to 'My profile', current_user %></li>
      <li class="white-link"><%= link_to 'Edit profile', edit_user_path(current_user) %></li>
      <li class="white-link"><%= link_to 'Other users', users_path %></li>
      <li class="divider"></li>
      <li class="white-link"><%= link_to 'Display mode', display_path %></li>
      <li class="divider"></li>
      <li class="white-link"><%= link_to 'Log out', logout_path, method: 'delete' %></li>
    <% end %>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to image_tag("cyhoeddwn_favicon_big_transparent.png", size: "40"), root_path %>
    <% if logged_in? %>
      <button class="navbar-toggler small" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
          <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2z"/>
        </svg>
      </button>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="main_container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/no_hf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'noticeboards/display_header' %>
    <div class="main_container">
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>